### PR TITLE
Add a java linter that will check that code is formtted correctly.

### PR DESCRIPTION
**Pull request by ndmckinley**

### CODE REVIEW

**Comment by ndmckinley** [comment]
Clarification - if you have a fork-based workflow and there are no changes needed, the check will pass.  So it's not the death of fork-based workflows, just means that auto-repair isn't available for them.

**Review by carolinedanzi — COMMENTED** [review]
I'm new to reviewing github PRs, so just a question: it seems to me there are files here that don't relate to adding the Java formatter - is that correct or am I missing context/looking in the wrong place? (ex: AsyncController, CountController, etc.)

**Comment by hmhsu** [comment]
> I'm new to reviewing github PRs, so just a question: it seems to me there are files here that don't relate to adding the Java formatter - is that correct or am I missing context/looking in the wrong place? (ex: AsyncController, CountController, etc.)

I think those files are changed to appease linter complaints.

**Comment by ndmckinley** [comment]
@hmhsu is right.  :) That commit was made automatically by the formatter - those are pre-existing format errors.  The formatter runs on all the code, not just changed code, so the initial submit will include the changes to appease it.

**Comment by bion** [comment]
@ndmckinley another approach would be to have a linting check which fails the build if code isn't formatted properly and leave it up to the dev to run the formatter. Thoughts?

**Comment by ndmckinley** [comment]
whoops, closed the wrong one.  :)

**Comment by ndmckinley** [comment]
Right, of course - it fails because of the formatting errors.

**Comment by ndmckinley** [comment]
#19 includes the formatter - approve that and then I'll rebase this on top of main and we'll see the linter pass.

**Comment by ndmckinley** [comment]
@bion @hmhsu @carolinedanzi This is now ready for review!  Had to remove import sorting since the sbt plugin doesn't support that.  Seems like not-a-big-deal to me, do you agree?  Or is that an important part of the system?

**Review by hmhsu — APPROVED** [review]
Re skipping import sorting - that sounds good to me, but I will leave it up to Bion.

Given we are not committing auto-formatted code, please update the PR title (or the final merge message) to reflect that. Otherwise LGTM.

**Comment by bion** [comment]
> Had to remove import sorting since the sbt plugin doesn't support that. Seems like not-a-big-deal to me, do you agree? Or is that an important part of the system?

That's a bit of a surprise since our internal code formatter catches it. I think keeping them alphabetically sorted is helpful, particularly since wildcard imports are banned. Most editors have a means of doing this as well if the plugin won't.

**Comment by bion** [comment]
Thoughts on leaving the alphabetical imports check in place for now? Seems the downside is people having to figure it out on their own.

**Comment by ndmckinley** [comment]
I think it's probably better to have unsorted imports than to allow the linter to fail on code that's been run through the autoformatter.  I think there's a chance that the autoformatter is choking on the existing wildcard imports and that's why it's failing to sort them - I haven't been able to find a reason that it's failing or any logging output yet, but that's my current suspicion.  I will dig into that next if import sorting is important to you - ideally I'd do it in the next PR, though, since it's going to involve some further experimentation and it'd be a little easier if I had the GHA linter already configured.

**Comment by bion** [comment]
> ideally I'd do it in the next PR

That's totally reasonable, feel free to merge this PR

**Comment by ndmckinley** [comment]
Thanks, filed #23.

**Pull request merged**
