### PR TITLE
Restructure Cloudformation into nested stacks

### PR DESCRIPTION
**Pull request by ndmckinley**
### Description
This doesn't modify any of the resources, simply spreads them into stacks that we can reason about a little nicer, and creates a deploy script.

Still no tests - going to do that next.

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [x] Extended the README / documentation, if necessary

### Issue(s)
none

### CODE REVIEW

**Comment by ndmckinley** [comment]
Also, would you mind checking on this commit instead?  I think I *might* prefer it as yaml over json...  let me know what you think.

https://github.com/seattle-uat/universal-application-tool/compare/main...ndmckinley:restructure-yaml

**Review by hmhsu — APPROVED** [review]
Looks good!

**Comment by hmhsu** [comment]
> Also, would you mind checking on this commit ~instead~ also? I think I _might_ prefer it as yaml over json... let me know what you think.
> 
> [main...ndmckinley:restructure-yaml](https://github.com/seattle-uat/universal-application-tool/compare/main...ndmckinley:restructure-yaml)

Opps, I just see this now.

**Comment by ndmckinley** [comment]
No worries, I'll wait to merge til you decide your preference!

**Comment by hmhsu** [comment]
YAML also LGTM. I remember it supports comments while JSON doesn't? Based on that YAML seems more desirable. I am fine either.

**Comment by ndmckinley** [comment]
Okay, YAML it is.  :)

**Pull request merged**
